name: Nodejs AWS EC2 Workflow

on:
  push:
    branches:
      - main
    paths:
      - "nodejs-aws-ec2/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and deploy
        # This action is used to connect to the remote server
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          HOST_NAME: ${{ secrets.HOST_NAME }}
          USER_NAME: ${{ secrets.USER_NAME }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} '

            # Now we are in the remote server
            cd /home/ubuntu/terraform-realworld-exercises &&
            echo "Deploying the app" &&
            git pull &&
            cd nodejs-aws-ec2 &&
            npm install &&
            pm2 restart index.js
          '
